#!/bin/bash
cd ~/Desktop/FaithFinderApp

cat > src/lib/filters.ts << 'EOF'
export const DENOMINATIONS = [
  'All',
  'Non-Denominational',
  'Catholic',
  'Baptist',
  'Southern Baptist',
  'Methodist',
  'United Methodist',
  'Lutheran',
  'Presbyterian',
  'Episcopal',
  'Anglican',
  'Pentecostal',
  'Assemblies of God',
  'Charismatic',
  'Apostolic',
  'AME',
  'AME Zion',
  'Church of God',
  'Church of Christ',
  'Evangelical',
  'Reformed',
  'Calvinist',
  'Adventist',
  'Seventh-day Adventist',
  'Orthodox',
  'Greek Orthodox',
  'Nazarene',
  'Wesleyan',
  'Mennonite',
  'Quaker',
  'Moravian',
  'Salvation Army',
  'Christian Science',
  'Disciples of Christ',
  'Foursquare',
  'Vineyard',
  'Brethren',
  'Covenant',
  'Alliance',
];

export const STATES = [
  'All States',
  'AL - Alabama',
  'AK - Alaska',
  'AZ - Arizona',
  'AR - Arkansas',
  'CA - California',
  'CO - Colorado',
  'CT - Connecticut',
  'DE - Delaware',
  'FL - Florida',
  'GA - Georgia',
  'HI - Hawaii',
  'ID - Idaho',
  'IL - Illinois',
  'IN - Indiana',
  'IA - Iowa',
  'KS - Kansas',
  'KY - Kentucky',
  'LA - Louisiana',
  'ME - Maine',
  'MD - Maryland',
  'MA - Massachusetts',
  'MI - Michigan',
  'MN - Minnesota',
  'MS - Mississippi',
  'MO - Missouri',
  'MT - Montana',
  'NE - Nebraska',
  'NV - Nevada',
  'NH - New Hampshire',
  'NJ - New Jersey',
  'NM - New Mexico',
  'NY - New York',
  'NC - North Carolina',
  'ND - North Dakota',
  'OH - Ohio',
  'OK - Oklahoma',
  'OR - Oregon',
  'PA - Pennsylvania',
  'RI - Rhode Island',
  'SC - South Carolina',
  'SD - South Dakota',
  'TN - Tennessee',
  'TX - Texas',
  'UT - Utah',
  'VT - Vermont',
  'VA - Virginia',
  'WA - Washington',
  'WV - West Virginia',
  'WI - Wisconsin',
  'WY - Wyoming',
];
EOF
echo "filters.ts done"
